name: Auto-merge Dependabot PRs

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge when checks pass
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          delete_branch: true
